In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [46]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)
test_data = np.array([[1.01,-1.0,1.0],[1.0,1.0,2.0]])

Solution
===

In [33]:
print(test_data)

[[ 1. -1.  1.]
 [ 1.  1.  2.]]


In [47]:
def standardize(x):
    ''' param x: matrix where each row is a sample and all columns are features 
    '''
    # calc mean & std
    mean = np.mean(x, axis=0)
    std = np.std(x, axis=0)

    # make sure none of the features has zero variance, to avoid divison by zero.
    # these should be eliminated anyways since zero variance features are of no use to the model
    assert not (np.any(std==0)) 
    
    #normalize
    x = x - mean
    x = x/ std
    
    return x



In [51]:
std_data = standardize(data)

In [52]:
print(std_data)
print(np.mean(std_data, axis=0))
print( np.std(std_data, axis=0))

[[ 1.0775774  -1.34411605  0.31525355  0.80665878  0.24128662]
 [-1.81711634 -0.77630186  0.74088404 -1.25592235 -1.42276759]
 [ 0.62228127  1.64254169 -1.797091   -0.03521894  1.51565143]
 [ 0.23651339  0.90075228 -0.83122987  1.40786459  1.11788073]
 [-0.13414844 -0.95529104 -0.55795449  0.54097769  0.01136005]
 [-0.70898541  0.56774371 -0.08900028  0.45652209  0.65726018]
 [ 1.2571441   0.25993298  1.23775021 -0.72176808 -1.4141686 ]
 [-1.41508984 -1.04555188  0.96949701 -1.69076861  0.75969247]
 [-0.10744434  1.21308427 -1.14296098  1.19109415 -0.35450368]
 [ 0.98926822 -0.46279408  1.15485183 -0.69943932 -1.11169162]]
[-1.66533454e-16  4.99600361e-17 -2.22044605e-17  1.11022302e-17
  3.33066907e-16]
[1. 1. 1. 1. 1.]
